services:
  airflow:
    image: apache/airflow:2.7.3
    container_name: airflow_superstore
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    command: standalone
